### ISSUE TITLE
79-udev-komplete.rules is missed in repo

### ISSUE THREAD

**Issue by KottV** [GoaSkin/qKontrol#1]
Hi,

Thank you for your work!
So I'm gonna package qKontrol, but didn't find the udev rules example in repo. It can be gotten from https://www.native-instruments.com/forum/threads/qkontrol-an-open-source-mapping-editor-for-the-komplete-kontrol-mk2-on-linux-and-mac.333887/page-4#post-1895023
Maybe worth to put it there?

**Comment by GoaSkin** [comment]
UDEV rules file has been placed into the source subdirectory of the repository.

**Comment by KottV** [comment]
Thanks!
